In [1]:
import numpy as np

In [6]:
Z = np.random.randint(0, 2, (6,6))
M = np.zeros(Z.shape)

In [7]:
Z

array([[1, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1]])

In [8]:
N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
     Z[1:-1, 0:-2]                 + Z[1:-1, 2:] +
     Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])

In [12]:
N

array([[6, 5, 4, 5],
       [6, 7, 6, 6],
       [5, 5, 6, 7],
       [3, 4, 5, 6]])

In [13]:
N == 4

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]], dtype=bool)

In [15]:
Z= np.arange(50)

In [17]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.array([1,2,0,0,4,0]) > 0

array([ True,  True, False, False,  True, False], dtype=bool)

In [20]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [21]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
np.random.random((3,3,3))

array([[[ 0.246632  ,  0.28947303,  0.41399389],
        [ 0.29339155,  0.82492919,  0.13339673],
        [ 0.92639452,  0.7935954 ,  0.97205871]],

       [[ 0.36817777,  0.05625315,  0.41449741],
        [ 0.14283159,  0.49497972,  0.39665213],
        [ 0.05587973,  0.5561603 ,  0.42038513]],

       [[ 0.82339646,  0.7966778 ,  0.74048087],
        [ 0.83363317,  0.28253091,  0.15715914],
        [ 0.53795934,  0.10701014,  0.71882718]]])

In [26]:
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.0320805532353
0.997497779061


In [27]:
np.random.random(30).mean()

0.4408417109179425

In [34]:
z = np.ones((3,3))
z[1:-1,1:-1] = 0
z

array([[ 1.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  1.]])

In [35]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [36]:
Z = np.random.randint(0, 10, (10))

In [38]:
Z[(Z > 3) & (Z<=8)] *= -1

In [39]:
Z

array([-6,  0,  0,  0, -5, -6,  2,  9, -4,  9])

In [40]:
Z = np.random.uniform(0,10,10)
np.floor(Z)

array([ 3.,  9.,  0.,  4.,  2.,  9.,  7.,  7.,  0.,  3.])

In [48]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
L = np.sqrt(X**2+Y**2)
A = np.arctan(X,Y)

In [52]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([ 0.25701699,  0.07364662,  0.14313521,  0.28011774,  0.91123979,
        0.00483263,  0.        ,  0.95550923,  0.45761049,  0.84124848])

In [60]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
index

15

In [61]:
np.zeros(10, [ ('position', [ ('x', float, 1),
                              ('y', float, 1)]),
               ('color',    [ ('r', float, 1),
                              ('g', float, 1),
                              ('b', float, 1)])])

array([(( 0.,  0.), ( 0.,  0.,  0.)), (( 0.,  0.), ( 0.,  0.,  0.)),
       (( 0.,  0.), ( 0.,  0.,  0.)), (( 0.,  0.), ( 0.,  0.,  0.)),
       (( 0.,  0.), ( 0.,  0.,  0.)), (( 0.,  0.), ( 0.,  0.,  0.)),
       (( 0.,  0.), ( 0.,  0.,  0.)), (( 0.,  0.), ( 0.,  0.,  0.)),
       (( 0.,  0.), ( 0.,  0.,  0.)), (( 0.,  0.), ( 0.,  0.,  0.))], 
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [67]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(X.shape)
D = np.sqrt(X**2+Y**2)
sigma, mu = 1.0, 0.0
np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

(10, 10)


array([[ 0.36787944,  0.44822088,  0.51979489,  0.57375342,  0.60279818,
         0.60279818,  0.57375342,  0.51979489,  0.44822088,  0.36787944],
       [ 0.44822088,  0.54610814,  0.63331324,  0.69905581,  0.73444367,
         0.73444367,  0.69905581,  0.63331324,  0.54610814,  0.44822088],
       [ 0.51979489,  0.63331324,  0.73444367,  0.81068432,  0.85172308,
         0.85172308,  0.81068432,  0.73444367,  0.63331324,  0.51979489],
       [ 0.57375342,  0.69905581,  0.81068432,  0.89483932,  0.9401382 ,
         0.9401382 ,  0.89483932,  0.81068432,  0.69905581,  0.57375342],
       [ 0.60279818,  0.73444367,  0.85172308,  0.9401382 ,  0.98773022,
         0.98773022,  0.9401382 ,  0.85172308,  0.73444367,  0.60279818],
       [ 0.60279818,  0.73444367,  0.85172308,  0.9401382 ,  0.98773022,
         0.98773022,  0.9401382 ,  0.85172308,  0.73444367,  0.60279818],
       [ 0.57375342,  0.69905581,  0.81068432,  0.89483932,  0.9401382 ,
         0.9401382 ,  0.89483932,  0.81068432

In [83]:
X = np.arange(50).reshape(5, 10)
X-X.mean(axis=1, keepdims=True)

array([[-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5]])

In [84]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 3 4]
 [9 7 1]
 [0 2 3]]
[[0 2 3]
 [6 3 4]
 [9 7 1]]


In [95]:
#Z = np.random.randint(0,3,(3,10))
#Z= np.zeros((3, 10))
Z = np.eye(3)
print(Z)
Z.any(axis=0).any()

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


True

In [99]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
Z[np.abs(Z-z).argmin()]

[ 0.30175122  0.32114889  0.93973939  0.81600954  0.8279667   0.24223682
  0.07310813  0.08321152  0.50250778  0.57981099]


0.50250777569543315

In [105]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
len(np.unique(F))

4

In [109]:
Z = np.arange(4*4*4).reshape(4,4,4)
print(Z)
Z.sum(axis=0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


array([[ 96, 100, 104, 108],
       [112, 116, 120, 124],
       [128, 132, 136, 140],
       [144, 148, 152, 156]])